export const reportsConfigRoleWise: any = {
    Admin: [
        {
            id: "position",
            reportName: "Position",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            tableActions:['view_positions'],
            api:'report/Position',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            dialogTableColumns:[
                { field: 'servertime', header: 'Server Time', type:'date' },
                { field: 'devicetime', header: 'Device Time', type:'date' },
                { field: 'vaild', header: 'GPS' },
                { field: 'latitude', header: 'Latitude' },
                { field: 'longitude', header: 'Longitude' },
                { field: 'speed', header: 'Speed' },
                { field: 'course', header: 'Direction' },
              ],
              dialogDataKey: 'positions',
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "event",
            reportName: "Event",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Alert/CountAndType',
             tableColumns: [
                 { field: 'device', subfield: 'vahanSno', header: 'Vehicle Sno', nested: true, },
                 { field: 'device', subfield: 'imei', header: 'IMEI', nested: true, },
                 { field: 'vehicle', subfield: 'vehicleNo', header: 'Vehicle Name', nested: true, },
                 { field: 'alert', subfield: 'accident', header: 'Accident', nested: true },
                 { field: 'alert', subfield: 'door', header: 'Door', nested: true },
                 { field: 'alert', subfield: 'aallDown', header: 'Aall Down', nested: true },
                 { field: 'alert', subfield: 'geofenceEnter', header: 'Geofence Enter', nested: true },
                 { field: 'alert', subfield: 'geofenceExit', header: 'Geofence Exit', nested: true },
                 { field: 'alert', subfield: 'jamming', header: 'Jamming', nested: true },
                 { field: 'alert', subfield: 'lowBattery', header: 'Low Battery', nested: true },
                 { field: 'alert', subfield: 'overspeed', header: 'Overspeed', nested: true },
                 { field: 'alert', subfield: 'powerCut', header: 'Power Cut', nested: true },
                 { field: 'alert', subfield: 'sos', header: 'Sos', nested: true },
                 { field: 'alert', subfield: 'tampering', header: 'Tampering', nested: true },
                 { field: 'alert', subfield: 'vibration', header: 'Vibration', nested: true },
                 { field: 'alert', subfield: 'hardAcceleration', header: 'Hard Acceleration', nested: true },
                 { field: 'alert', subfield: 'hardBraking', header: 'Hard Braking', nested: true },
                 { field: 'alert', subfield: 'hardCornering', header: 'Hard Cornering', nested: true }
             ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "expire_soon",
            reportName: "Expire Soon",
            filters: {
                state:true,
                rto: true,
                oem: true,
                days: true,
                specificVehicle: true,
                date: { enabled: false },               
            },
            api:'report/Expired/ExpireSoon',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },

            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "expired_vehicle",
            reportName: "Expired Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true, disableCurrentDate: true }
            },
            tableActions:['send_message'],
            api:'report/Expired/Expired',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno.', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "vehicle_status",
            reportName: "Vehicle Status",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            independent:true,
            autoGenerate:{ enabled:true},
            api:'report/VehicleStatus/WithGraphPie',
            chart: {pie:true, bar:true},
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'lastFixTime', header: 'Last Fix Time', type: 'date' },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "sos",
            reportName: "SOS",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true },               
            },
            api:'report/Alert/Sos',
            lottie: { display: true, path: '/assets/lottie/alert.json' },
            tableColumns:[
                { field: 'sos', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "overspeed",
            reportName: "Overspeed",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            lottie: { display: true, path: '/assets/lottie/alert.json' },
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "speed_violation",
            reportName: "Speed Violation",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "distance",
            reportName: "Distance",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "summary",
            reportName: "Summary",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },

         {
            id: "alert",
            reportName: "Alert",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Alert/CountAndType',
             tableColumns: [
                 { field: 'device', subfield: 'vahanSno', header: 'Vehicle Sno', nested: true, },
                 { field: 'device', subfield: 'imei', header: 'IMEI', nested: true, },
                 { field: 'vehicle', subfield: 'vehicleNo', header: 'Vehicle Name', nested: true, },
                 { field: 'alert', subfield: 'accident', header: 'Accident', nested: true },
                 { field: 'alert', subfield: 'door', header: 'Door', nested: true },
                 { field: 'alert', subfield: 'aallDown', header: 'Aall Down', nested: true },
                 { field: 'alert', subfield: 'geofenceEnter', header: 'Geofence Enter', nested: true },
                 { field: 'alert', subfield: 'geofenceExit', header: 'Geofence Exit', nested: true },
                 { field: 'alert', subfield: 'jamming', header: 'Jamming', nested: true },
                 { field: 'alert', subfield: 'lowBattery', header: 'Low Battery', nested: true },
                 { field: 'alert', subfield: 'overspeed', header: 'Overspeed', nested: true },
                 { field: 'alert', subfield: 'powerCut', header: 'Power Cut', nested: true },
                 { field: 'alert', subfield: 'sos', header: 'Sos', nested: true },
                 { field: 'alert', subfield: 'tampering', header: 'Tampering', nested: true },
                 { field: 'alert', subfield: 'vibration', header: 'Vibration', nested: true },
                 { field: 'alert', subfield: 'hardAcceleration', header: 'Hard Acceleration', nested: true },
                 { field: 'alert', subfield: 'hardBraking', header: 'Hard Braking', nested: true },
                 { field: 'alert', subfield: 'hardCornering', header: 'Hard Cornering', nested: true }
             ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "offline_vehicle",
            reportName: "Offline Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                daysRange: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/OfflineListWithGraphPie',
            chart: {pie:true, bar:true},
            autoGenerate:{ enabled:true, defaultValue:{ label: "> 30 day",value: [30, 0]} },
            tableColumns:[
                { field: 'fixTime', header: 'Fix Time', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "device_installation",
            reportName: "Vehicle Installation",
            filters: {
                state:true,
                rto: true,
                oem: true,
                date: { enabled: true, disableFutureDate: true }
            },
            api:'report/DeviceInstallation/WithGraphPie',
            chart: {pie:true, bar:true},
            autoGenerate: { enabled:true, defaultValue: new Date(2024, 10, 27)},
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
    ],
    OEM: [
        {
            id: "position",
            reportName: "Position",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Position',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "event",
            reportName: "Event",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Event',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "expire_soon",
            reportName: "Expire Soon",
            filters: {
                state:true,
                rto: true,
                oem: true,
                days: true,
                specificVehicle: true,
                date: { enabled: false },               
            },
            api:'report/Expired/ExpireSoon',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },

            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "expired_vehicle",
            reportName: "Expired Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true, disableCurrentDate: true }
            },
            tableActions:['send_message'],
            api:'report/Expired/Expired',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno.', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "vehicle_status",
            reportName: "Vehicle Status",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/WithGraphPie',
            chart: {pie:true, bar:true},
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'lastFixTime', header: 'Last Fix Time', type: 'date' },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "sos",
            reportName: "SOS",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true },               
            },
            api:'report/Alert/Sos',
            tableColumns:[
                { field: 'sos', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "overspeed",
            reportName: "Overspeed",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "offline_vehicle",
            reportName: "Offline Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                daysRange: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/OfflineListWithGraphPie',
            chart: {pie:true, bar:true},
            tableColumns:[
                { field: 'fixTime', header: 'Fix Time', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
    ],
    Distributor: [
        {
            id: "position",
            reportName: "Position",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Position',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "event",
            reportName: "Event",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Event',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "expire_soon",
            reportName: "Expire Soon",
            filters: {
                state:true,
                rto: true,
                oem: true,
                days: true,
                specificVehicle: true,
                date: { enabled: false },               
            },
            api:'report/Expired/ExpireSoon',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },

            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "expired_vehicle",
            reportName: "Expired Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true, disableCurrentDate: true }
            },
            tableActions:['send_message'],
            api:'report/Expired/Expired',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno.', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "vehicle_status",
            reportName: "Vehicle Status",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/WithGraphPie',
            chart: {pie:true, bar:true},
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'lastFixTime', header: 'Last Fix Time', type: 'date' },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "sos",
            reportName: "SOS",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true },               
            },
            api:'report/Alert/Sos',
            tableColumns:[
                { field: 'sos', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "overspeed",
            reportName: "Overspeed",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "offline_vehicle",
            reportName: "Offline Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                daysRange: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/OfflineListWithGraphPie',
            chart: {pie:true, bar:true},
            tableColumns:[
                { field: 'fixTime', header: 'Fix Time', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
    ],
    Dealer: [
        {
            id: "position",
            reportName: "Position",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Position',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "event",
            reportName: "Event",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Event',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "expire_soon",
            reportName: "Expire Soon",
            filters: {
                state:true,
                rto: true,
                oem: true,
                days: true,
                specificVehicle: true,
                date: { enabled: false },               
            },
            api:'report/Expired/ExpireSoon',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },

            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "expired_vehicle",
            reportName: "Expired Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true, disableCurrentDate: true }
            },
            tableActions:['send_message'],
            api:'report/Expired/Expired',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno.', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "vehicle_status",
            reportName: "Vehicle Status",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/WithGraphPie',
            chart: {pie:true, bar:true},
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'lastFixTime', header: 'Last Fix Time', type: 'date' },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "sos",
            reportName: "SOS",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true },               
            },
            api:'report/Alert/Sos',
            tableColumns:[
                { field: 'sos', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "overspeed",
            reportName: "Overspeed",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "offline_vehicle",
            reportName: "Offline Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                daysRange: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/OfflineListWithGraphPie',
            chart: {pie:true, bar:true},
            tableColumns:[
                { field: 'fixTime', header: 'Fix Time', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
    ],
};
