export const reportsConfigRoleWise: any = {
    Admin: [
        {
            id: "position",
            reportName: "Position",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Position',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "event",
            reportName: "Event",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Event',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "expire_soon",
            reportName: "Expire Soon",
            filters: {
                state:true,
                rto: true,
                oem: true,
                days: true,
                specificVehicle: true,
                date: { enabled: false },               
            },
            api:'report/Expired/ExpireSoon',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },

            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "expired_vehicle",
            reportName: "Expired Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true, disableCurrentDate: true }
            },
            tableActions:['send_message'],
            api:'report/Expired/Expired',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno.', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "vehicle_status",
            reportName: "Vehicle Status",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus',
            tableColumns:[
                { field: 'vehicle', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'lastFixTime', header: 'Last Fix Time', type: 'date' },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "sos",
            reportName: "SOS",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true },               
            },
            api:'report/Alert/Sos',
            tableColumns:[
                { field: 'sos', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "overspeed",
            reportName: "Overspeed",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "offline_vehicle",
            reportName: "Offline Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                daysRange: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/OfflineList',
            tableColumns:[
                { field: 'fixTime', header: 'Fix Time', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
    ],
    OEM: [
        {
            id: "position",
            reportName: "Position",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Position',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "event",
            reportName: "Event",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Event',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "expire_soon",
            reportName: "Expire Soon",
            filters: {
                state:true,
                rto: true,
                oem: true,
                days: true,
                specificVehicle: true,
                date: { enabled: false },               
            },
            api:'report/Expired/ExpireSoon',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },

            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "expired_vehicle",
            reportName: "Expired Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true, disableCurrentDate: true }
            },
            tableActions:['send_message'],
            api:'report/Expired/Expired',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno.', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "vehicle_status",
            reportName: "Vehicle Status",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "sos",
            reportName: "SOS",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Alert/Sos',
            tableColumns:[
                { field: 'sos', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "overspeed",
            reportName: "Overspeed",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "offline_vehicle",
            reportName: "Offline Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                daysRange: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/OfflineList',
            tableColumns:[
                { field: 'fixTime', header: 'Fix Time', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
    ],
    Distributor: [
        {
            id: "position",
            reportName: "Position",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Position',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "event",
            reportName: "Event",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Event',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "expire_soon",
            reportName: "Expire Soon",
            filters: {
                state:true,
                rto: true,
                oem: true,
                days: true,
                specificVehicle: true,
                date: { enabled: false },               
            },
            api:'report/Expired/ExpireSoon',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },

            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "expired_vehicle",
            reportName: "Expire Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true, disableCurrentDate: true }
            },
            tableActions:['send_message'],
            api:'report/Expired/Expired',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno.', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "vehicle_status",
            reportName: "Vehicle Status",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "sos",
            reportName: "SOS",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Alert/Sos',
            tableColumns:[
                { field: 'sos', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "overspeed",
            reportName: "Overspeed",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "offline_vehicle",
            reportName: "Offline Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                daysRange: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/OfflineList',
            tableColumns:[
                { field: 'fixTime', header: 'Fix Time', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
    ],
    Dealer: [
        {
            id: "position",
            reportName: "Position",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Position',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "event",
            reportName: "Event",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Event',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
         {
            id: "expire_soon",
            reportName: "Expire Soon",
            filters: {
                state:true,
                rto: true,
                oem: true,
                days: true,
                specificVehicle: true,
                date: { enabled: false },               
            },
            api:'report/Expired/ExpireSoon',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },

            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "expired_vehicle",
            reportName: "Expire Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true, disableCurrentDate: true }
            },
            tableActions:['send_message'],
            api:'report/Expired/Expired',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vahan Sno.', nested: true, },
                { field: 'fitmentDate', header: 'Fitment Date', type: 'date' },
                { field: 'fitmentValidTill', header: 'Fitment Valid', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "vehicle_status",
            reportName: "Vehicle Status",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus',
            tableColumns:[
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
                { field: 'status', subfield:'status', header: 'Status' },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "sos",
            reportName: "SOS",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true },               
            },
            api:'report/Alert/Sos',
            tableColumns:[
                { field: 'sos', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'vehicle', subfield:'vehicleNo', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "overspeed",
            reportName: "Overspeed",
            filters: {
                state:true,
                rto: true,
                oem: true,
                specificVehicle: true,
                date: { enabled: true, disableFutureDate: true, disableCurrentDate: true }
            },
            api:'report/Alert/Overspeed',
            tableColumns:[
                { field: 'overspeed', header: 'Count' },
                { field: 'device', subfield:'vahanSno', header: 'Vehicle Sno', nested: true, },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
        {
            id: "offline_vehicle",
            reportName: "Offline Vehicle",
            filters: {
                state:true,
                rto: true,
                oem: true,
                daysRange: true,
                specificVehicle: true,
                date: { enabled: false, disableFutureDate: true }
            },
            api:'report/VehicleStatus/OfflineList',
            tableColumns:[
                { field: 'fixTime', header: 'Fix Time', type: 'date' },
                { field: 'device', subfield:'imei', header: 'IMEI', nested: true, },
                { field: 'device', subfield:'vehicleName', header: 'Vehicle Name', nested: true, },
                { field: 'oem', subfield:'name', header: 'OEM Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderName', header: 'Permit Holder Name', nested: true, },
                { field: 'permitHolder', subfield:'permitHolderMobile', header: 'Permit Holder Mobile No', nested: true, },
                { field: 'rto', subfield:'rtoName', header: 'RTO Name', nested: true, },
            ],
            globalFilterFields:['device.vahanSno', 'device.imei', 'device.vehicleName', 'oem.name', 'permitHolder.permitHolderName', 'rto.rtoName', 'status'],
        },
    ],
};
